apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: xcopy-pvc
  namespace: ${.POD_NAMESPACE}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: ${.STORAGE_CLASS_NAME}
  volumeMode: Block

