FROM registry.access.redhat.com/ubi9/go-toolset:1.19.10-4 as builder
ENV GOPATH=$APP_ROOT
COPY . .
RUN CGO_ENABLED=0 go build -buildvcs=false -o ova-provider-server github.com/konveyor/forklift-controller/cmd/ova-provider-server 

FROM quay.io/centos/centos:stream9-minimal
COPY --from=builder /opt/app-root/src/ova-provider-server /usr/local/bin/ova-provider-server
ENTRYPOINT ["/usr/local/bin/ova-provider-server"]