apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: forklift-populator-controller-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: forklift-populator-controller-role
subjects:
  - kind: ServiceAccount
    name: forklift-populator-controller
    namespace: system