#!/usr/bin/env bash
shopt -s nullglob

export LIBGUESTFS_PATH=/usr/lib64/guestfs
set -- "$LIBGUESTFS_PATH"/libguestfs-appliance.tar.xz
if [ -f "$1" ] ; then
    echo "Extracting libguestfs appliance..."
    APPLIANCE="/var/tmp/libguestfs-appliance"
    mkdir -p "$APPLIANCE"
    tar -xvJf "$1" -C "$APPLIANCE"
    LIBGUESTFS_PATH="$APPLIANCE/appliance"
fi

echo "Run virt-v2v with the following input:"
cat /mnt/v2v/input.xml

virt-v2v -v -x -i libvirtxml -o null --debug-overlays --no-copy --root=first /mnt/v2v/input.xml
[ $? != 0 ] && exit 1

echo "Conversion successful. Committing all overlays to local disks."
for OVERLAY in /var/tmp/*.qcow2
do
	if ! qemu-img commit -p "$OVERLAY"
	then
		echo Failed to commit overlay "$OVERLAY"!
		echo Unable to complete import!
		exit 1
	fi
done

echo "Commit successful. Cleaning up."
find /var/tmp -name '*.qcow2' -exec rm -f {} \;

exit 0
