version: "2"

linters:
  enable:
    - ginkgolinter
    - nilerr
    - nilnil
    - bodyclose
  settings:
    ginkgolinter:
      forbid-focus-container: true
  exclusions:
    paths:
      - vendor
      - pkg/lib/gob

formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    paths:
      - vendor
      - pkg/lib/gob
