issues:
  exclude-dirs:
    - vendor
    - pkg/lib/gob
linters:
  enable:
  - ginkgolinter
  - nilerr
  - nilnil
  - bodyclose
  - gofmt
  - goimports
linters-settings:
  ginkgolinter:
    forbid-focus-container: true
