package settings

import (
	"testing"
)

// Auto generated tests for TestMigration_VirtV2vInspectorExtraArgs
// Generated by: claude-4-5-opus
// Reviewed and uploaded by: @yaacov

// TestMigration_VirtV2vInspectorExtraArgs tests the parsing of the VIRT_V2V_INSPECTOR_EXTRA_ARGS
// environment variable into a JSON array string.
//
// The env var values look like CLI flags (e.g., "--verbose --debug") because they ARE CLI flags
// that will be passed to the virt-v2v-inspector tool. This test verifies the transformation:
//
//	Environment Variable              →  Stored as JSON Array
//	"--parallel 4 --verbose"          →  '["--parallel","4","--verbose"]'
//
// The parsing uses strings.Fields() to split on whitespace, then JSON-encodes the result.
// This allows operators to inject extra arguments into virt-v2v-inspector via environment
// variables without modifying code.
func TestMigration_VirtV2vInspectorExtraArgs(t *testing.T) {
	tests := []struct {
		name     string
		envValue string
		unsetEnv bool
		expected string
	}{
		{
			name:     "unset env defaults to empty array",
			envValue: "",
			unsetEnv: true,
			expected: "[]",
		},
		{
			name:     "empty string defaults to empty array",
			envValue: "",
			unsetEnv: false,
			expected: "[]",
		},
		{
			name:     "single arg",
			envValue: "--verbose",
			unsetEnv: false,
			expected: `["--verbose"]`,
		},
		{
			name:     "multiple args",
			envValue: "--arg1 --arg2",
			unsetEnv: false,
			expected: `["--arg1","--arg2"]`,
		},
		{
			name:     "args with values",
			envValue: "--parallel 4 --verbose",
			unsetEnv: false,
			expected: `["--parallel","4","--verbose"]`,
		},
		{
			name:     "multiple spaces between args are handled",
			envValue: "--arg1    --arg2",
			unsetEnv: false,
			expected: `["--arg1","--arg2"]`,
		},
		{
			name:     "leading and trailing whitespace trimmed",
			envValue: "  --arg1 --arg2  ",
			unsetEnv: false,
			expected: `["--arg1","--arg2"]`,
		},
		{
			name:     "tabs and newlines handled",
			envValue: "--arg1\t--arg2\n--arg3",
			unsetEnv: false,
			expected: `["--arg1","--arg2","--arg3"]`,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			// Set ROLE to inventory to skip MainRole-specific required env vars
			t.Setenv(Roles, InventoryRole)

			if tt.unsetEnv {
				// Don't set the env var at all (t.Setenv with empty would still set it)
				// We use a unique env var name manipulation isn't needed since
				// os.LookupEnv returns found=false if unset
			} else {
				t.Setenv(VirtV2vInspectorExtraArgs, tt.envValue)
			}

			var migration Migration
			err := migration.Load()
			if err != nil {
				t.Fatalf("Load() error = %v", err)
			}

			if migration.VirtV2vInspectorExtraArgs != tt.expected {
				t.Errorf("VirtV2vInspectorExtraArgs = %q, want %q",
					migration.VirtV2vInspectorExtraArgs, tt.expected)
			}
		})
	}
}

// TestMigration_VirtV2vExtraArgs tests the parsing of the VIRT_V2V_EXTRA_ARGS environment
// variable into a JSON array string. Similar to TestMigration_VirtV2vInspectorExtraArgs,
// these are CLI flags for the virt-v2v conversion tool (not the inspector).
func TestMigration_VirtV2vExtraArgs(t *testing.T) {
	tests := []struct {
		name     string
		envValue string
		unsetEnv bool
		expected string
	}{
		{
			name:     "unset env defaults to empty array",
			envValue: "",
			unsetEnv: true,
			expected: "[]",
		},
		{
			name:     "empty string defaults to empty array",
			envValue: "",
			unsetEnv: false,
			expected: "[]",
		},
		{
			name:     "single arg",
			envValue: "--parallel",
			unsetEnv: false,
			expected: `["--parallel"]`,
		},
		{
			name:     "multiple args with value",
			envValue: "--parallel 4",
			unsetEnv: false,
			expected: `["--parallel","4"]`,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			// Set ROLE to inventory to skip MainRole-specific required env vars
			t.Setenv(Roles, InventoryRole)

			if tt.unsetEnv {
				// Don't set the env var
			} else {
				t.Setenv(VirtV2vExtraArgs, tt.envValue)
			}

			var migration Migration
			err := migration.Load()
			if err != nil {
				t.Fatalf("Load() error = %v", err)
			}

			if migration.VirtV2vExtraArgs != tt.expected {
				t.Errorf("VirtV2vExtraArgs = %q, want %q",
					migration.VirtV2vExtraArgs, tt.expected)
			}
		})
	}
}

// TestMigration_ExtraArgsSeparation verifies that VirtV2vExtraArgs and VirtV2vInspectorExtraArgs
// are independently parsed and stored. This separation was introduced in PR #4509 to allow
// different CLI flags for the conversion tool vs the inspector tool.
func TestMigration_ExtraArgsSeparation(t *testing.T) {
	t.Run("conversion and inspector args are independent", func(t *testing.T) {
		t.Setenv(Roles, InventoryRole)
		t.Setenv(VirtV2vExtraArgs, "--parallel 4")
		t.Setenv(VirtV2vInspectorExtraArgs, "--verbose --debug")

		var migration Migration
		err := migration.Load()
		if err != nil {
			t.Fatalf("Load() error = %v", err)
		}

		expectedConversion := `["--parallel","4"]`
		expectedInspector := `["--verbose","--debug"]`

		if migration.VirtV2vExtraArgs != expectedConversion {
			t.Errorf("VirtV2vExtraArgs = %q, want %q",
				migration.VirtV2vExtraArgs, expectedConversion)
		}

		if migration.VirtV2vInspectorExtraArgs != expectedInspector {
			t.Errorf("VirtV2vInspectorExtraArgs = %q, want %q",
				migration.VirtV2vInspectorExtraArgs, expectedInspector)
		}
	})

	t.Run("conversion args set but inspector args unset", func(t *testing.T) {
		t.Setenv(Roles, InventoryRole)
		t.Setenv(VirtV2vExtraArgs, "--parallel 4")
		// VirtV2vInspectorExtraArgs is not set

		var migration Migration
		err := migration.Load()
		if err != nil {
			t.Fatalf("Load() error = %v", err)
		}

		if migration.VirtV2vExtraArgs != `["--parallel","4"]` {
			t.Errorf("VirtV2vExtraArgs = %q, want %q",
				migration.VirtV2vExtraArgs, `["--parallel","4"]`)
		}

		if migration.VirtV2vInspectorExtraArgs != "[]" {
			t.Errorf("VirtV2vInspectorExtraArgs = %q, want %q",
				migration.VirtV2vInspectorExtraArgs, "[]")
		}
	})

	t.Run("inspector args set but conversion args unset", func(t *testing.T) {
		t.Setenv(Roles, InventoryRole)
		// VirtV2vExtraArgs is not set
		t.Setenv(VirtV2vInspectorExtraArgs, "--verbose")

		var migration Migration
		err := migration.Load()
		if err != nil {
			t.Fatalf("Load() error = %v", err)
		}

		if migration.VirtV2vExtraArgs != "[]" {
			t.Errorf("VirtV2vExtraArgs = %q, want %q",
				migration.VirtV2vExtraArgs, "[]")
		}

		if migration.VirtV2vInspectorExtraArgs != `["--verbose"]` {
			t.Errorf("VirtV2vInspectorExtraArgs = %q, want %q",
				migration.VirtV2vInspectorExtraArgs, `["--verbose"]`)
		}
	})
}

// TestMigration_ServiceAccount tests loading the MIGRATION_SERVICE_ACCOUNT environment
// variable. When set, it provides a cluster-wide default ServiceAccount for migration pods.
// Priority: Plan.Spec.ServiceAccount > Settings.Migration.ServiceAccount > "" (namespace default).
func TestMigration_ServiceAccount(t *testing.T) {
	tests := []struct {
		name     string
		envValue string
		unsetEnv bool
		expected string
	}{
		{
			name:     "unset env defaults to empty",
			envValue: "",
			unsetEnv: true,
			expected: "",
		},
		{
			name:     "empty string remains empty",
			envValue: "",
			unsetEnv: false,
			expected: "",
		},
		{
			name:     "loads SA name when set",
			envValue: "global-migration-sa",
			unsetEnv: false,
			expected: "global-migration-sa",
		},
		{
			name:     "handles hyphenated SA name",
			envValue: "my-custom-sa",
			unsetEnv: false,
			expected: "my-custom-sa",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Setenv(Roles, InventoryRole)

			if !tt.unsetEnv {
				t.Setenv(MigrationServiceAccount, tt.envValue)
			}

			var migration Migration
			err := migration.Load()
			if err != nil {
				t.Fatalf("Load() error = %v", err)
			}

			if migration.ServiceAccount != tt.expected {
				t.Errorf("ServiceAccount = %q, want %q",
					migration.ServiceAccount, tt.expected)
			}
		})
	}
}

// TestMigration_VirtV2vImageXFS tests the loading of the VIRT_V2V_IMAGE_RHEL9 environment
// variable for XFS compatibility mode. This XFS-compatible image supports XFSv4 filesystems
// and can be selected per-plan via the XfsCompatibility flag.
func TestMigration_VirtV2vImageXFS(t *testing.T) {
	const xfsImage = "quay.io/kubev2v/forklift-virt-v2v-rhel9:latest"

	tests := []struct {
		name        string
		envValue    string
		unsetEnv    bool
		role        string
		expectError bool
		expected    string
	}{
		{
			name:        "loads XFS image when set in non-main role",
			envValue:    xfsImage,
			unsetEnv:    false,
			role:        InventoryRole,
			expectError: false,
			expected:    xfsImage,
		},
		{
			name:        "loads XFS image when set in main role",
			envValue:    xfsImage,
			unsetEnv:    false,
			role:        MainRole,
			expectError: false,
			expected:    xfsImage,
		},
		{
			name:        "returns error when unset in main role",
			envValue:    "",
			unsetEnv:    true,
			role:        MainRole,
			expectError: true,
			expected:    "",
		},
		{
			name:        "allows unset in inventory role",
			envValue:    "",
			unsetEnv:    true,
			role:        InventoryRole,
			expectError: false,
			expected:    "",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Setenv(Roles, tt.role)

			// Set required env vars for MainRole
			if tt.role == MainRole {
				t.Setenv(VirtV2vImage, "quay.io/kubev2v/forklift-virt-v2v:latest")
				t.Setenv(VirtV2vDontRequestKVM, "false")
				t.Setenv(VirtCustomizeConfigMap, "virt-customize-config")
				t.Setenv(OvirtOsConfigMap, "ovirt-os-map")
				t.Setenv(VsphereOsConfigMap, "vsphere-os-map")
			}

			if !tt.unsetEnv {
				t.Setenv(VirtV2vImageXFS, tt.envValue)
			}

			// Load global Settings.Role first since Migration.Load() checks it
			Settings.Role = Role{}
			err := Settings.Role.Load()
			if err != nil {
				t.Fatalf("Failed to load role: %v", err)
			}

			var migration Migration
			err = migration.Load()

			if tt.expectError {
				if err == nil {
					t.Errorf("Expected error but got none")
				}
			} else {
				if err != nil {
					t.Fatalf("Load() unexpected error = %v", err)
				}

				if migration.VirtV2vImageXFS != tt.expected {
					t.Errorf("VirtV2vImageXFS = %q, want %q",
						migration.VirtV2vImageXFS, tt.expected)
				}
			}
		})
	}
}

// TestMigration_XfsAndStandardImages verifies that both standard and XFS images
// can be loaded simultaneously and are stored independently.
func TestMigration_XfsAndStandardImages(t *testing.T) {
	const (
		standardImage = "quay.io/kubev2v/forklift-virt-v2v:latest"
		xfsImage      = "quay.io/kubev2v/forklift-virt-v2v:rhel9-xfs"
	)

	t.Run("both images load independently", func(t *testing.T) {
		t.Setenv(Roles, InventoryRole)

		t.Setenv(VirtV2vImage, standardImage)
		t.Setenv(VirtV2vImageXFS, xfsImage)

		var migration Migration
		err := migration.Load()
		if err != nil {
			t.Fatalf("Load() error = %v", err)
		}

		if migration.VirtV2vImage != standardImage {
			t.Errorf("VirtV2vImage = %q, want %q",
				migration.VirtV2vImage, standardImage)
		}

		if migration.VirtV2vImageXFS != xfsImage {
			t.Errorf("VirtV2vImageXFS = %q, want %q",
				migration.VirtV2vImageXFS, xfsImage)
		}
	})
}
