package settings

import (
	"testing"
)

// Auto generated tests for TestMigration_VirtV2vInspectorExtraArgs
// Generated by: claude-4-5-opus
// Reviewed and uploaded by: @yaacov

// TestMigration_VirtV2vInspectorExtraArgs tests the parsing of the VIRT_V2V_INSPECTOR_EXTRA_ARGS
// environment variable into a JSON array string.
//
// The env var values look like CLI flags (e.g., "--verbose --debug") because they ARE CLI flags
// that will be passed to the virt-v2v-inspector tool. This test verifies the transformation:
//
//	Environment Variable              →  Stored as JSON Array
//	"--parallel 4 --verbose"          →  '["--parallel","4","--verbose"]'
//
// The parsing uses strings.Fields() to split on whitespace, then JSON-encodes the result.
// This allows operators to inject extra arguments into virt-v2v-inspector via environment
// variables without modifying code.
func TestMigration_VirtV2vInspectorExtraArgs(t *testing.T) {
	tests := []struct {
		name     string
		envValue string
		unsetEnv bool
		expected string
	}{
		{
			name:     "unset env defaults to empty array",
			envValue: "",
			unsetEnv: true,
			expected: "[]",
		},
		{
			name:     "empty string defaults to empty array",
			envValue: "",
			unsetEnv: false,
			expected: "[]",
		},
		{
			name:     "single arg",
			envValue: "--verbose",
			unsetEnv: false,
			expected: `["--verbose"]`,
		},
		{
			name:     "multiple args",
			envValue: "--arg1 --arg2",
			unsetEnv: false,
			expected: `["--arg1","--arg2"]`,
		},
		{
			name:     "args with values",
			envValue: "--parallel 4 --verbose",
			unsetEnv: false,
			expected: `["--parallel","4","--verbose"]`,
		},
		{
			name:     "multiple spaces between args are handled",
			envValue: "--arg1    --arg2",
			unsetEnv: false,
			expected: `["--arg1","--arg2"]`,
		},
		{
			name:     "leading and trailing whitespace trimmed",
			envValue: "  --arg1 --arg2  ",
			unsetEnv: false,
			expected: `["--arg1","--arg2"]`,
		},
		{
			name:     "tabs and newlines handled",
			envValue: "--arg1\t--arg2\n--arg3",
			unsetEnv: false,
			expected: `["--arg1","--arg2","--arg3"]`,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			// Set ROLE to inventory to skip MainRole-specific required env vars
			t.Setenv(Roles, InventoryRole)

			if tt.unsetEnv {
				// Don't set the env var at all (t.Setenv with empty would still set it)
				// We use a unique env var name manipulation isn't needed since
				// os.LookupEnv returns found=false if unset
			} else {
				t.Setenv(VirtV2vInspectorExtraArgs, tt.envValue)
			}

			var migration Migration
			err := migration.Load()
			if err != nil {
				t.Fatalf("Load() error = %v", err)
			}

			if migration.VirtV2vInspectorExtraArgs != tt.expected {
				t.Errorf("VirtV2vInspectorExtraArgs = %q, want %q",
					migration.VirtV2vInspectorExtraArgs, tt.expected)
			}
		})
	}
}

// TestMigration_VirtV2vExtraArgs tests the parsing of the VIRT_V2V_EXTRA_ARGS environment
// variable into a JSON array string. Similar to TestMigration_VirtV2vInspectorExtraArgs,
// these are CLI flags for the virt-v2v conversion tool (not the inspector).
func TestMigration_VirtV2vExtraArgs(t *testing.T) {
	tests := []struct {
		name     string
		envValue string
		unsetEnv bool
		expected string
	}{
		{
			name:     "unset env defaults to empty array",
			envValue: "",
			unsetEnv: true,
			expected: "[]",
		},
		{
			name:     "empty string defaults to empty array",
			envValue: "",
			unsetEnv: false,
			expected: "[]",
		},
		{
			name:     "single arg",
			envValue: "--parallel",
			unsetEnv: false,
			expected: `["--parallel"]`,
		},
		{
			name:     "multiple args with value",
			envValue: "--parallel 4",
			unsetEnv: false,
			expected: `["--parallel","4"]`,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			// Set ROLE to inventory to skip MainRole-specific required env vars
			t.Setenv(Roles, InventoryRole)

			if tt.unsetEnv {
				// Don't set the env var
			} else {
				t.Setenv(VirtV2vExtraArgs, tt.envValue)
			}

			var migration Migration
			err := migration.Load()
			if err != nil {
				t.Fatalf("Load() error = %v", err)
			}

			if migration.VirtV2vExtraArgs != tt.expected {
				t.Errorf("VirtV2vExtraArgs = %q, want %q",
					migration.VirtV2vExtraArgs, tt.expected)
			}
		})
	}
}

// TestMigration_ExtraArgsSeparation verifies that VirtV2vExtraArgs and VirtV2vInspectorExtraArgs
// are independently parsed and stored. This separation was introduced in PR #4509 to allow
// different CLI flags for the conversion tool vs the inspector tool.
func TestMigration_ExtraArgsSeparation(t *testing.T) {
	t.Run("conversion and inspector args are independent", func(t *testing.T) {
		t.Setenv(Roles, InventoryRole)
		t.Setenv(VirtV2vExtraArgs, "--parallel 4")
		t.Setenv(VirtV2vInspectorExtraArgs, "--verbose --debug")

		var migration Migration
		err := migration.Load()
		if err != nil {
			t.Fatalf("Load() error = %v", err)
		}

		expectedConversion := `["--parallel","4"]`
		expectedInspector := `["--verbose","--debug"]`

		if migration.VirtV2vExtraArgs != expectedConversion {
			t.Errorf("VirtV2vExtraArgs = %q, want %q",
				migration.VirtV2vExtraArgs, expectedConversion)
		}

		if migration.VirtV2vInspectorExtraArgs != expectedInspector {
			t.Errorf("VirtV2vInspectorExtraArgs = %q, want %q",
				migration.VirtV2vInspectorExtraArgs, expectedInspector)
		}
	})

	t.Run("conversion args set but inspector args unset", func(t *testing.T) {
		t.Setenv(Roles, InventoryRole)
		t.Setenv(VirtV2vExtraArgs, "--parallel 4")
		// VirtV2vInspectorExtraArgs is not set

		var migration Migration
		err := migration.Load()
		if err != nil {
			t.Fatalf("Load() error = %v", err)
		}

		if migration.VirtV2vExtraArgs != `["--parallel","4"]` {
			t.Errorf("VirtV2vExtraArgs = %q, want %q",
				migration.VirtV2vExtraArgs, `["--parallel","4"]`)
		}

		if migration.VirtV2vInspectorExtraArgs != "[]" {
			t.Errorf("VirtV2vInspectorExtraArgs = %q, want %q",
				migration.VirtV2vInspectorExtraArgs, "[]")
		}
	})

	t.Run("inspector args set but conversion args unset", func(t *testing.T) {
		t.Setenv(Roles, InventoryRole)
		// VirtV2vExtraArgs is not set
		t.Setenv(VirtV2vInspectorExtraArgs, "--verbose")

		var migration Migration
		err := migration.Load()
		if err != nil {
			t.Fatalf("Load() error = %v", err)
		}

		if migration.VirtV2vExtraArgs != "[]" {
			t.Errorf("VirtV2vExtraArgs = %q, want %q",
				migration.VirtV2vExtraArgs, "[]")
		}

		if migration.VirtV2vInspectorExtraArgs != `["--verbose"]` {
			t.Errorf("VirtV2vInspectorExtraArgs = %q, want %q",
				migration.VirtV2vInspectorExtraArgs, `["--verbose"]`)
		}
	})
}
