---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: imageio-populator-account
  namespace: konveyor-forklift
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: imageio-populator-role
rules:
  - apiGroups: [""]
    resources: [persistentvolumes]
    verbs: [get, list, watch, patch]
  - apiGroups: [""]
    resources: [persistentvolumeclaims]
    verbs: [get, list, watch, patch, create, delete]
  - apiGroups: [""]
    resources: [pods]
    verbs: [get, list, watch, create, delete]
  - apiGroups: [storage.k8s.io]
    resources: [storageclasses]
    verbs: [get, list, watch]
  - apiGroups: [""]
    resources: [secrets]
    verbs: [list, watch, get]
  - apiGroups: [forklift.konveyor.io]
    resources: [ovirtimageiopopulators]
    verbs: [get, list, watch]
  - apiGroups: ["cdi.kubevirt.io"]
    resources: ["datavolumes"]
    verbs: [get, list, watch, create, delete, patch]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: imageio-populator-binding
subjects:
  - kind: ServiceAccount
    name: imageio-populator-account
    namespace: konveyor-forklift
  - kind: ServiceAccount
    name: default
    namespace: konveyor-forklift
  - kind: ServiceAccount
    name: default
    namespace: default
roleRef:
  kind: ClusterRole
  name: imageio-populator-role
  apiGroup: rbac.authorization.k8s.io
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: imageio-populator
  namespace: konveyor-forklift
spec:
  selector:
    matchLabels:
      app: imageio-populator
  template:
    metadata:
      labels:
        app: imageio-populator
    spec:
      serviceAccount: imageio-populator-account
      containers:
        - name: imageio-populator
          image: quay.io/bzlotnik/ovirt-imageio-populator:latest
          imagePullPolicy: Always
          args:
            - --mode=controller
            - --image-name=quay.io/bzlotnik/ovirt-imageio-populator:latest
            - --http-endpoint=:8080
          ports:
            - containerPort: 8080
              name: http-endpoint
              protocol: TCP
---
kind: VolumePopulator
apiVersion: populator.storage.k8s.io/v1beta1
metadata:
  name: ovirt-volume-populator
sourceKind:
  group: forklift.konveyor.io
  kind: OvirtVolumePopulator
