---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: forklift-operator
  namespace: system
spec:
  template:
    spec:
      containers:
        - name: manager
          imagePullPolicy: IfNotPresent
