apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- resources/forklift-operator.yaml
- resources/forklift-controller.yaml
- resources/forklift-api.yaml
- resources/forklift-default.yaml
configMapGenerator:
- behavior: create
  envs:
  - deploy.env
  name: forklift-operator-env
replacements:
- source:
    fieldPath: data.OPERATOR_NAMESPACE
    kind: ConfigMap
    name: forklift-operator-env
    version: v1
  targets:
  - fieldPaths:
    - subjects.*.namespace
    select:
      group: rbac.authorization.k8s.io
      kind: RoleBinding
      version: v1
- source:
    fieldPath: data.REGISTRY_ORG
    kind: ConfigMap
    name: forklift-operator-env
    version: v1
  targets:
  - fieldPaths:
    - metadata.namespace
    select:
      group: rbac.authorization.k8s.io
      kind: RoleBinding
      version: v1
