---
kind: Plan
apiVersion: forklift.konveyor.io/v1alpha1
metadata:
  name: test
  namespace: openshift-migration
spec:
  provider:
    source:
      namespace: ""
      name: ""
    destination:
      namespace: ""
      name: ""
