---
kind: Provisioner
apiVersion: forklift.konveyor.io/v1alpha1
metadata:
  name: cinder
  namespace: openshift-migration
spec:
  name: kubernetes.io/cinder
  volumeModes:
  - name: Block
    priority: 0
    accessModes:
    - name: ReadWriteOnce
      priority: 0
    - name: ReadWriteMany
      priority: 1
  - name: Filesystem
    priority: 1
    accessModes:
    - name: ReadWriteOnce
      priority: 0
    - name: ReadWriteMany
      priority: 1
