kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: imageio-populator-role
rules:
  - apiGroups: [""]
    resources: [persistentvolumes]
    verbs: [get, list, watch, patch]
  - apiGroups: [""]
    resources: [persistentvolumeclaims]
    verbs: [get, list, watch, patch, create, delete]
  - apiGroups: [""]
    resources: [pods]
    verbs: [get, list, watch, create, delete]
  - apiGroups: [storage.k8s.io]
    resources: [storageclasses]
    verbs: [get, list, watch]
  - apiGroups: [""]
    resources: [secrets]
    verbs: [list, watch, get]
  - apiGroups: [forklift.konveyor.io]
    resources: [ovirtimageiopopulators]
    verbs: [get, list, watch]