# permissions for end users to view forkliftcontrollers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: forkliftcontroller-viewer-role
rules:
- apiGroups:
  - forklift.konveyor.io
  resources:
  - forkliftcontrollers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - forklift.konveyor.io
  resources:
  - forkliftcontrollers/status
  verbs:
  - get
