---
- block:

  - name: "Set UI plugin feature state"
    set_fact:
      ui_plugin_state: "present"
    when: feature_ui_plugin|bool

  - name: "Set validation feature state"
    set_fact:
      validation_state: "present"
    when: feature_validation|bool

  - name: "Set volume populator feature state"
    set_fact:
      volume_populator_state: "present"
    when: feature_volume_populator|bool

  - name: "Load cluster API groups"
    set_fact:
      api_groups: "{{ lookup('k8s', cluster_info='api_groups') }}"

  - when: "'route.openshift.io' not in api_groups"
    block:
    - name: "Enable k8s cluster environment"
      set_fact:
        k8s_cluster: true

    - name: "Obtain k8s cluster version"
      set_fact:
        k8s_cluster_version: "{{ lookup('k8s', cluster_info='version').kubernetes.gitVersion }}"

  - name: "Setup controller config map"
    k8s:
      state : present
      definition: "{{ lookup('template', 'controller/configmap-controller.yml.j2') }}"

  - name: "Setup operating systems config map for oVirt"
    k8s:
      state : present
      definition: "{{ lookup('template', 'controller/configmap-osmap-ovirt.yml.j2') }}"

  - name: "Setup operating systems config map for vSphere"
    k8s:
      state : present
      definition: "{{ lookup('template', 'controller/configmap-osmap-vsphere.yml.j2') }}"

  - name: "Setup inventory service"
    k8s:
      state: present
      definition: "{{ lookup('template', 'controller/service-inventory.yml.j2') }}"

  - name: "Setup forklift-services service"
    k8s:
      state: present
      definition: "{{ lookup('template', 'api/service-services.yml.j2') }}"

  - name: "Setup controller deployment"
    k8s:
      state : present
      definition: "{{ lookup('template', 'controller/deployment-controller.yml.j2') }}"
      merge_type: "merge"

  - name: "Setup inventory route"
    k8s:
      state: present
      definition: "{{ lookup('template', 'controller/route-inventory.yml.j2') }}"
    when: not k8s_cluster|bool

  - name: "Setup forklift-services route"
    k8s:
      state: present
      definition: "{{ lookup('template', 'api/route-services.yml.j2') }}"
    when: not k8s_cluster|bool

  - name: "Setup forklift-controller security context constraints"
    k8s:
      state: present
      definition: "{{ lookup('template', 'controller/controller-scc.yml.j2') }}"
    when: not k8s_cluster|bool

  - when: not k8s_cluster|bool
    block:
    - name: "Setup metrics service"
      k8s:
        state: present
        definition: "{{ lookup('template', 'monitor/service-metrics.yml.j2') }}"
        
    - name: "Setup metrics service monitor"
      k8s:
        state: present
        definition: "{{ lookup('template', 'monitor/servicemonitor-metrics.yml.j2') }}"

    - name: "Setup migration recording rules"
      k8s:
        state: present
        definition: "{{ lookup('template', 'monitor/recordingrole-migrations.yml.j2') }}"

    - name: "Add monitoring label to namespace"
      k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: "{{ app_namespace }}"
            labels:
              openshift.io/cluster-monitoring: "true"

  - when: feature_volume_populator|bool
    block:
    - name: "Setup populator controller deployment"
      k8s:
        state: "{{ volume_populator_state }}"
        definition: "{{ lookup('template', 'populator/deployment-populator-controller.yml.j2') }}"

  - when: k8s_cluster|bool
    block:
    - name: "Create a trusted CA issuer"
      k8s:
        state: present
        definition: "{{ lookup('template', 'cert-manager-trusted-ca.yml.j2') }}"
    - name: "Configure webhook certificate on K8s"
      k8s:
        state: present
        definition: "{{ lookup('template', 'api/ca.yml.j2') }}"
    - name: "Configure forklift-services certificate on K8s"
      k8s:
        state: present
        definition: "{{ lookup('template', 'api/services-ca.yml.j2') }}"
    - name: "Configure validation certificate on K8s"
      k8s:
        state: present
        definition: "{{ lookup('template', 'validation/ca.yml.j2') }}"
    - name: "Configure inventory certificate on K8s"
      k8s:
        state: present
        definition: "{{ lookup('template', 'controller/ca.yml.j2') }}"

  - name: "Setup api service"
    k8s:
      state: present
      definition: "{{ lookup('template', 'api/service-forklift-api.yml.j2') }}"

  - name: "Setup api deployment"
    k8s:
      state: present
      definition: "{{ lookup('template', 'api/deployment-forklift-api.yml.j2') }}"

  - name: "Setup webhook configuration"
    include_tasks: webhooks.yml
    vars:
      webhook_state: "present"

  - name: "Setup default provider"
    k8s:
      state: present
      definition: "{{ lookup('template', 'controller/provider-host.yml.j2') }}"
    when: "'kubevirt.io' in api_groups"

  - when: feature_validation|bool
    block:
    - name: "Setup validation service"
      k8s:
        state: "{{ validation_state }}"
        definition: "{{ lookup('template', 'validation/service-validation.yml.j2') }}"

    - name: "Setup validation config map"
      k8s:
        state: "{{ validation_state }}"
        definition: "{{ lookup('template', 'validation/configmap-validation.yml.j2') }}"

    - name: "Setup validation deployment"
      k8s:
        state: "{{ validation_state }}"
        definition: "{{ lookup('template', 'validation/deployment-validation.yml.j2') }}"

  - when: feature_ui_plugin|bool and not k8s_cluster|bool
    block:

    - name: "Setup UI plugin configmap"
      k8s:
        state: "{{ ui_plugin_state }}"
        definition: "{{ lookup('template', 'ui-plugin/configmap-ui-plugin.yml.j2') }}"

    - name: "Setup UI plugin service"
      k8s:
        state: "{{ ui_plugin_state }}"
        definition: "{{ lookup('template', 'ui-plugin/service-ui-plugin.yml.j2') }}"

    - name: "Setup UI plugin deployment"
      k8s:
        state: "{{ ui_plugin_state }}"
        definition: "{{ lookup('template', 'ui-plugin/deployment-ui-plugin.yml.j2') }}"

    - name: "Setup console plugin"
      k8s:
        state: "{{ ui_plugin_state }}"
        definition: "{{ lookup('template', 'ui-plugin/console-plugin.yml.j2') }}"

    - name: "Get cluster console information"
      k8s_info:
        api_version: operator.openshift.io/v1
        kind: console
        name: cluster
      register: console_operator

    - name: "Set console_plugins variable"
      set_fact:
        console_plugins: "{{ console_operator['resources'][0]['spec']['plugins'] | default([]) }}"

    - name: "Enable console plugin"
      k8s:
        api_version: operator.openshift.io/v1
        kind: console
        name: cluster
        state: present
        definition:
          spec:
            plugins: "{{ console_plugins + [ui_plugin_console_name] }}"
      when: ui_plugin_console_name not in console_plugins

  - name: "Create controller service-account token Secret for download vddk tar"
    k8s:
      state: present
      definition: "{{ lookup('template', 'controller/secret-forklift-controller-token.yml.j2') }}"

  - name: "Create VDDK BuildConfig"
    k8s:
      state: present
      definition: "{{ lookup('template', 'controller/buildconfig-vddk.yml.j2') }}"

  - name: "Create VDDK ImageStream"
    k8s:
      state: present
      definition: "{{ lookup('template', 'controller/imagestream-vddk.yml.j2') }}"

  - when: not feature_ui_plugin|bool
    name: "Cleanup {{ ui_plugin_service_name }} if disabled"
    include_tasks: cleanup.yml
    loop: "{{ forklift_resources }}"
    loop_control:
      loop_var: resource_kind
    vars:
      feature_label: "{{ ui_plugin_service_name }}"

  - when: not feature_validation|bool
    name: "Cleanup {{ validation_service_name }} if disabled"
    include_tasks: cleanup.yml
    loop: "{{ forklift_resources }}"
    loop_control:
      loop_var: resource_kind
    vars:
      feature_label: "{{ validation_service_name }}"

  - name: "Delete must-gather-api deployment"
    k8s:
      api_version: apps/v1
      kind: deployment
      namespace: "{{ app_namespace }}"
      name: forklift-must-gather-api
      state: absent
    when: finalize is not defined

- block:
  - name: "Remove webhook configuration"
    include_tasks: webhooks.yml
    vars:
      webhook_state: "absent"

  - name: "Remove console plugin"
    k8s:
      state: absent
      definition: "{{ lookup('template', 'ui-plugin/console-plugin.yml.j2') }}"

  when: finalize is defined
