FROM registry.access.redhat.com/ubi8/go-toolset:1.18.9-8 as builder
ENV GOPATH=$APP_ROOT

COPY go.mod ./
COPY go.sum ./
COPY cmd/ovirt-populator/ovirt-populator.go ./
COPY vendor/ ./vendor/
# When debugging by replacing the lib-volume-populator with a local modified copy
# COPY . ./

RUN CGO_ENABLED=0 go build -o ovirt-populator

FROM quay.io/centos/centos:stream9-minimal
COPY --from=builder /opt/app-root/src/ovirt-populator /usr/local/bin
RUN microdnf install -y gcc python3-pip python3-devel libxml2-devel openssl-devel libcurl-devel qemu-img && microdnf clean all
RUN pip install ovirt-engine-sdk-python ovirt-imageio

ENTRYPOINT ["/usr/local/bin/ovirt-populator"]
