FROM golang:1.19.3-alpine3.16 as builder
WORKDIR /app

COPY . ./
WORKDIR /app/cmd/ovirt-populator

# When debugging by replacing the lib-volume-populator with a local modified copy
# COPY . ./

RUN CGO_ENABLED=0 go build -o /ovirt-populator

FROM quay.io/centos/centos:stream9-minimal
COPY --from=builder /ovirt-populator /
RUN microdnf install -y gcc python3-pip python3-devel libxml2-devel openssl-devel libcurl-devel qemu-img
RUN pip install ovirt-engine-sdk-python ovirt-imageio

ENTRYPOINT ["/ovirt-populator"]
