apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- resources/catalogsource.yaml
- resources/operatorgroup.yaml
- resources/subscription.yaml
configMapGenerator:
- behavior: create
  envs:
  - deploy.env
  name: forklift-operator-env
replacements:
- source:
    fieldPath: data.OPERATOR_NAMESPACE
    kind: ConfigMap
    name: forklift-operator-env
    version: v1
  targets:
  - fieldPaths:
    - metadata.namespace
    - spec.targetNamespaces.0
    select:
      group: operators.coreos.com
      kind: OperatorGroup
      name: migration
      version: v1
  - fieldPaths:
    - metadata.namespace
    select:
      group: operators.coreos.com
      kind: Subscription
      version: v1alpha1
  - fieldPaths:
    - metadata.namespace
    select:
      group: forklift.konveyor.io
      kind: ForkliftController
      version: v1beta1
- source:
    fieldPath: data.OPERATOR_NAME
    kind: ConfigMap
    name: forklift-operator-env
    version: v1
  targets:
  - fieldPaths:
    - metadata.name
    - spec.name
    select:
      group: operators.coreos.com
      kind: Subscription
      version: v1alpha1
- source:
    fieldPath: data.CATALOG_NAMESPACE
    kind: ConfigMap
    name: forklift-operator-env
    version: v1
  targets:
  - fieldPaths:
    - metadata.namespace
    select:
      group: operators.coreos.com
      kind: CatalogSource
      version: v1alpha1
  - fieldPaths:
    - spec.sourceNamespace
    select:
      group: operators.coreos.com
      kind: Subscription
      version: v1alpha1
- source:
    fieldPath: data.CATALOG_NAME
    kind: ConfigMap
    name: forklift-operator-env
    version: v1
  targets:
  - fieldPaths:
    - metadata.name
    select:
      group: operators.coreos.com
      kind: CatalogSource
      version: v1alpha1
  - fieldPaths:
    - spec.source
    select:
      group: operators.coreos.com
      kind: Subscription
      version: v1alpha1
- source:
    fieldPath: data.CATALOG_IMAGE
    kind: ConfigMap
    name: forklift-operator-env
    version: v1
  targets:
  - fieldPaths:
    - spec.image
    select:
      group: operators.coreos.com
      kind: CatalogSource
      version: v1alpha1
- source:
    fieldPath: data.CATALOG_DISPLAY_NAME
    kind: ConfigMap
    name: forklift-operator-env
    version: v1
  targets:
  - fieldPaths:
    - spec.displayName
    select:
      group: operators.coreos.com
      kind: CatalogSource
      version: v1alpha1
- source:
    fieldPath: data.CATALOG_PUBLISHER
    kind: ConfigMap
    name: forklift-operator-env
    version: v1
  targets:
  - fieldPaths:
    - spec.publisher
    select:
      group: operators.coreos.com
      kind: CatalogSource
      version: v1alpha1
- source:
    fieldPath: data.SUBSCRIPTION_CHANNEL
    kind: ConfigMap
    name: forklift-operator-env
    version: v1
  targets:
  - fieldPaths:
    - spec.channel
    select:
      group: operators.coreos.com
      kind: Subscription
      version: v1alpha1
