FROM registry.access.redhat.com/ubi8/go-toolset:1.18.9-8 as builder
ENV GOPATH=$APP_ROOT

COPY go.mod ./
COPY go.sum ./
COPY cmd/openstack-populator/openstack-populator.go ./
RUN go mod download
RUN go build -o openstack-populator

FROM registry.access.redhat.com/ubi9-minimal:9.1.0-1760.1675784957
COPY --from=builder /opt/app-root/src/openstack-populator /usr/local/bin

ENTRYPOINT ["/usr/local/bin/openstack-populator"]
