apiVersion: v1
kind: Pod
metadata:
  labels:
    app: forklift-api
  name: forklift-api
  namespace: openshift-mtv
spec:
  containers:
  - command:
    - /usr/local/bin/forklift-api
    image: image-registry.openshift-image-registry.svc:5000/openshift/api:devel
    imagePullPolicy: Always
    name: main
    ports:
    - containerPort: 9876
      name: webhook-server
      protocol: TCP
    resources:
      limits:
        cpu: 500m
        memory: 800Mi
      requests:
        cpu: 100m
        memory: 250Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/forklift-api
      name: forklift-api-crt
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    seLinuxOptions:
      level: s0:c25,c0
  serviceAccount: forklift-controller
  serviceAccountName: forklift-controller
  terminationGracePeriodSeconds: 10
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  - effect: NoSchedule
    key: node.kubernetes.io/memory-pressure
    operator: Exists
  volumes:
  - name: forklift-api-crt
    secret:
      defaultMode: 420
      secretName: forklift-api-crt
