apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: forklift-api
  namespace: ""
  annotations:
    service.beta.openshift.io/inject-cabundle: "true"
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: forklift-api
      namespace: openshift-mtv
      path: /secret-validate
      port: 443
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: secret.forklift.konveyor
  objectSelector:
    matchLabels:
      createdForResourceType: providers
  namespaceSelector: {}
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - secrets
    scope: '*'
  sideEffects: None
  timeoutSeconds: 20
