apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: REGISTRY_ORG_PLACEHOLDER
  name: forklift-catalog-default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:image-puller
subjects:
- kind: ServiceAccount
  name: default
  namespace: CATALOG_NAMESPACE_PLACEHOLDER

