apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- resources/catalog.yaml
configMapGenerator:
- behavior: create
  envs:
  - deploy.env
  name: forklift-operator-env
replacements:
- source:
    fieldPath: data.REGISTRY_ORG
    kind: ConfigMap
    name: forklift-operator-env
    version: v1
  targets:
  - fieldPaths:
    - metadata.namespace
    select:
      group: rbac.authorization.k8s.io
      kind: RoleBinding
      version: v1
- source:
    fieldPath: data.CATALOG_NAMESPACE
    kind: ConfigMap
    name: forklift-operator-env
    version: v1
  targets:
  - fieldPaths:
    - subjects.0.namespace
    select:
      group: rbac.authorization.k8s.io
      kind: RoleBinding
      version: v1
- source:
    fieldPath: data.CATALOG_NAME
    kind: ConfigMap
    name: forklift-operator-env
    version: v1
  targets:
  - fieldPaths:
    - subjects.0.name
    select:
      group: rbac.authorization.k8s.io
      kind: RoleBinding
      version: v1
