# Dry-run bundle: downstream-based (Containerfile-dry-run uses .downstream_manifests + relatedImages).
# Test staged components only (registry.stage.redhat.io + release.conf). Does not replace upstream or downstream.
# Output: forklift-operator-bundle-dry-run-2-10:{{revision}}
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/kubev2v/forklift?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: "{{revision}}"
    build.appstudio.redhat.com/target_branch: "{{target_branch}}"
    pipelinesascode.tekton.dev/cancel-in-progress: "false"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "push" && target_branch == "release-2.10" && ( "operator/.downstream_manifests".pathChanged() || "operator/related_images.yaml".pathChanged() || "operator/config/manifests/***".pathChanged() || ".tekton/forklift-operator-bundle-dry-run-*.yaml".pathChanged() || "build/forklift-operator-bundle/Containerfile-dry-run".pathChanged() || "build/release.conf".pathChanged() )
  creationTimestamp:
  labels:
    appstudio.openshift.io/application: forklift-operator-2-10
    appstudio.openshift.io/component: forklift-operator-bundle-dry-run-2-10
    pipelines.appstudio.openshift.io/type: build
  name: forklift-operator-bundle-dry-run-2-10-on-push
  namespace: rh-mtv-1-tenant
spec:
  params:
    - name: git-url
      value: "{{source_url}}"
    - name: revision
      value: "{{revision}}"
    - name: output-image
      value: quay.io/redhat-user-workloads/rh-mtv-1-tenant/forklift-operator-2-10/forklift-operator-bundle-dry-run-2-10:{{revision}}
    - name: dockerfile
      value: build/forklift-operator-bundle/Containerfile-dry-run
    - name: path-context
      value: .
    - name: build-source-image
      value: "true"
    - name: prefetch-input
      value: '[{"type": "gomod", "path": ".konflux/forklift-operator-bundle"}]'
    - name: build-args-file
      value: build/release.conf
    - name: build-args
      value:
        - "REVISION={{revision}}"
        - "CONTROLLER_IMAGE=registry.stage.redhat.io/migration-toolkit-virtualization/mtv-controller-rhel9:{{revision}}"
        - "API_IMAGE=registry.stage.redhat.io/migration-toolkit-virtualization/mtv-api-rhel9:{{revision}}"
        - "VIRT_V2V_IMAGE=registry.stage.redhat.io/migration-toolkit-virtualization/mtv-virt-v2v-rhel10:{{revision}}"
        - "OPERATOR_IMAGE=registry.stage.redhat.io/migration-toolkit-virtualization/mtv-rhel9-operator:{{revision}}"
        - "POPULATOR_CONTROLLER_IMAGE=registry.stage.redhat.io/migration-toolkit-virtualization/mtv-populator-controller-rhel9:{{revision}}"
        - "OVIRT_POPULATOR_IMAGE=registry.stage.redhat.io/migration-toolkit-virtualization/mtv-rhv-populator-rhel8:{{revision}}"
        - "OPENSTACK_POPULATOR_IMAGE=registry.stage.redhat.io/migration-toolkit-virtualization/mtv-openstack-populator-rhel9:{{revision}}"
        - "VSPHERE_XCOPY_VOLUME_POPULATOR_IMAGE=registry.stage.redhat.io/migration-toolkit-virtualization/mtv-vsphere-xcopy-volume-populator-rhel9:{{revision}}"
        - "MUST_GATHER_IMAGE=registry.stage.redhat.io/migration-toolkit-virtualization/mtv-must-gather-rhel8:{{revision}}"
        - "UI_PLUGIN_IMAGE=registry.stage.redhat.io/migration-toolkit-virtualization/mtv-console-plugin-rhel9:{{revision}}"
        - "CLI_DOWNLOAD_IMAGE=registry.stage.redhat.io/migration-toolkit-virtualization/mtv-cli-download-rhel9:{{revision}}"
        - "OVA_PROVIDER_SERVER_IMAGE=registry.stage.redhat.io/migration-toolkit-virtualization/mtv-ova-provider-server-rhel9:{{revision}}"
        - "VALIDATION_IMAGE=registry.stage.redhat.io/migration-toolkit-virtualization/mtv-validation-rhel9:{{revision}}"
        - "OVA_PROXY_IMAGE=registry.stage.redhat.io/migration-toolkit-virtualization/mtv-ova-proxy-rhel9:{{revision}}"
  pipelineSpec:
    description: |
      Dry-run: downstream-based bundle ( .downstream_manifests + relatedImages ) with staged
      component images (registry.stage.redhat.io + release.conf). For upstream use Containerfile;
      for production downstream use Containerfile-downstream.
    finally:
      - name: show-sbom
        params:
          - name: IMAGE_URL
            value: $(tasks.build-image-index.results.IMAGE_URL)
        taskRef:
          params:
            - name: name
              value: show-sbom
            - name: bundle
              value: quay.io/konflux-ci/tekton-catalog/task-show-sbom:0.1@sha256:e2c1b4eac642f32e91f3bc5d3cb48c5c70888aaf45c3650d9ea34573de7a7fd5
            - name: kind
              value: task
          resolver: bundles
    params:
      - description: Source Repository URL
        name: git-url
        type: string
      - default: ""
        description: Revision of the Source Repository
        name: revision
        type: string
      - description: Fully Qualified Output Image
        name: output-image
        type: string
      - default: .
        description: Path to the source code of an application's component from where to build image.
        name: path-context
        type: string
      - default: Dockerfile
        description: Path to the Dockerfile inside the context specified by parameter path-context
        name: dockerfile
        type: string
      - default: "false"
        description: Skip checks against built image
        name: skip-checks
        type: string
      - default: "true"
        description: Execute the build with network isolation
        name: hermetic
        type: string
      - default: ""
        description: Build dependencies to be prefetched by Cachi2
        name: prefetch-input
        type: string
      - default: ""
        description: Image tag expiration time, time values could be something like 1h, 2d, 3w for hours, days, and weeks, respectively.
        name: image-expires-after
      - default: "false"
        description: Build a source image.
        name: build-source-image
        type: string
      - default: "false"
        description: Add built image into an OCI image index
        name: build-image-index
        type: string
      - default: []
        description: Array of --build-arg values ("arg=value" strings) for buildah
        name: build-args
        type: array
      - default: ""
        description: Path to a file with build arguments for buildah, see https://www.mankier.com/1/buildah-build#--build-arg-file
        name: build-args-file
        type: string
      - default: "false"
        description: Whether to enable privileged mode, should be used only with remote VMs
        name: privileged-nested
        type: string
      - name: buildah-format
        default: docker
        type: string
        description: The format for the resulting image's mediaType. Valid values are oci or docker.
    results:
      - description: ""
        name: IMAGE_URL
        value: $(tasks.build-image-index.results.IMAGE_URL)
      - description: ""
        name: IMAGE_DIGEST
        value: $(tasks.build-image-index.results.IMAGE_DIGEST)
      - description: ""
        name: CHAINS-GIT_URL
        value: $(tasks.clone-repository.results.url)
      - description: ""
        name: CHAINS-GIT_COMMIT
        value: $(tasks.clone-repository.results.commit)
    tasks:
      - name: init
        taskRef:
          params:
            - name: name
              value: init
            - name: bundle
              value: quay.io/konflux-ci/tekton-catalog/task-init:0.3@sha256:aa6f8632cc23d605c5942505ff1d00280db16a6fda5c4c56c4ed9ae936b5fbc6
            - name: kind
              value: task
          resolver: bundles
      - name: clone-repository
        params:
          - name: url
            value: $(params.git-url)
          - name: revision
            value: $(params.revision)
          - name: ociStorage
            value: $(params.output-image).git
          - name: ociArtifactExpiresAfter
            value: $(params.image-expires-after)
        runAfter:
          - init
        taskRef:
          params:
            - name: name
              value: git-clone-oci-ta
            - name: bundle
              value: quay.io/konflux-ci/tekton-catalog/task-git-clone-oci-ta:0.1@sha256:306b69e6db435ad4a7cf258b6219d9b998eb37da44f5e9ac882ac86a08109154
            - name: kind
              value: task
          resolver: bundles
        workspaces:
          - name: basic-auth
            workspace: git-auth
      - name: prefetch-dependencies
        params:
          - name: input
            value: $(params.prefetch-input)
          - name: SOURCE_ARTIFACT
            value: $(tasks.clone-repository.results.SOURCE_ARTIFACT)
          - name: ociStorage
            value: $(params.output-image).prefetch
          - name: ociArtifactExpiresAfter
            value: $(params.image-expires-after)
        runAfter:
          - clone-repository
        taskRef:
          params:
            - name: name
              value: prefetch-dependencies-oci-ta
            - name: bundle
              value: quay.io/konflux-ci/tekton-catalog/task-prefetch-dependencies-oci-ta:0.2@sha256:c664a6df6514b59c3ce53570b0994b45af66ecc89ba2a8e41834eae0622addf6
            - name: kind
              value: task
          resolver: bundles
        workspaces:
          - name: git-basic-auth
            workspace: git-auth
          - name: netrc
            workspace: netrc
      - name: build-container
        params:
          - name: IMAGE
            value: $(params.output-image)
          - name: DOCKERFILE
            value: $(params.dockerfile)
          - name: CONTEXT
            value: $(params.path-context)
          - name: HERMETIC
            value: $(params.hermetic)
          - name: PREFETCH_INPUT
            value: $(params.prefetch-input)
          - name: IMAGE_EXPIRES_AFTER
            value: $(params.image-expires-after)
          - name: COMMIT_SHA
            value: $(tasks.clone-repository.results.commit)
          - name: BUILD_ARGS
            value:
              - $(params.build-args[*])
          - name: BUILD_ARGS_FILE
            value: $(params.build-args-file)
          - name: PRIVILEGED_NESTED
            value: $(params.privileged-nested)
          - name: SOURCE_URL
            value: $(tasks.clone-repository.results.url)
          - name: SOURCE_ARTIFACT
            value: $(tasks.prefetch-dependencies.results.SOURCE_ARTIFACT)
          - name: CACHI2_ARTIFACT
            value: $(tasks.prefetch-dependencies.results.CACHI2_ARTIFACT)
          - name: BUILDAH_FORMAT
            value: $(params.buildah-format)
        runAfter:
          - prefetch-dependencies
        taskRef:
          params:
            - name: name
              value: buildah-oci-ta
            - name: bundle
              value: quay.io/konflux-ci/tekton-catalog/task-buildah-oci-ta:0.8@sha256:ba9564699ca5dc84abb1307bda07ecf42058e4a153b3f1d4fd0d2e511d42a44d
            - name: kind
              value: task
          resolver: bundles
      - name: build-image-index
        params:
          - name: IMAGE
            value: $(params.output-image)
          - name: COMMIT_SHA
            value: $(tasks.clone-repository.results.commit)
          - name: IMAGE_EXPIRES_AFTER
            value: $(params.image-expires-after)
          - name: ALWAYS_BUILD_INDEX
            value: $(params.build-image-index)
          - name: IMAGES
            value:
              - $(tasks.build-container.results.IMAGE_URL)@$(tasks.build-container.results.IMAGE_DIGEST)
          - name: BUILDAH_FORMAT
            value: $(params.buildah-format)
        runAfter:
          - build-container
        taskRef:
          params:
            - name: name
              value: build-image-index
            - name: bundle
              value: quay.io/konflux-ci/tekton-catalog/task-build-image-index:0.2@sha256:8c422a5380a3d877257003dee153190322af84fe6f4f25e9eee7d8bf61a62577
            - name: kind
              value: task
          resolver: bundles
      - name: build-source-image
        params:
          - name: BINARY_IMAGE
            value: $(tasks.build-image-index.results.IMAGE_URL)
          - name: BINARY_IMAGE_DIGEST
            value: $(tasks.build-image-index.results.IMAGE_DIGEST)
          - name: SOURCE_ARTIFACT
            value: $(tasks.prefetch-dependencies.results.SOURCE_ARTIFACT)
          - name: CACHI2_ARTIFACT
            value: $(tasks.prefetch-dependencies.results.CACHI2_ARTIFACT)
        runAfter:
          - build-image-index
        taskRef:
          params:
            - name: name
              value: source-build-oci-ta
            - name: bundle
              value: quay.io/konflux-ci/tekton-catalog/task-source-build-oci-ta:0.3@sha256:c35ba219390d77a48ee19347e5ee8d13e5c23e3984299e02291d6da1ed8a986c
            - name: kind
              value: task
          resolver: bundles
        when:
          - input: $(params.build-source-image)
            operator: in
            values:
              - "true"
      - name: ecosystem-cert-preflight-checks
        params:
          - name: image-url
            value: $(tasks.build-image-index.results.IMAGE_URL)
        runAfter:
          - build-image-index
        taskRef:
          params:
            - name: name
              value: ecosystem-cert-preflight-checks
            - name: bundle
              value: quay.io/konflux-ci/tekton-catalog/task-ecosystem-cert-preflight-checks:0.2@sha256:33b7133c0c132c361295c30947f73bd45a3a3b62a24b83f3d8cd7c71f757828c
            - name: kind
              value: task
          resolver: bundles
        when:
          - input: $(params.skip-checks)
            operator: in
            values:
              - "false"
      - name: apply-tags
        params:
          - name: IMAGE_URL
            value: $(tasks.build-image-index.results.IMAGE_URL)
          - name: IMAGE_DIGEST
            value: $(tasks.build-image-index.results.IMAGE_DIGEST)
        runAfter:
          - build-image-index
        taskRef:
          params:
            - name: name
              value: apply-tags
            - name: bundle
              value: quay.io/konflux-ci/tekton-catalog/task-apply-tags:0.3@sha256:510b6d2a3b188adeb716e49566b57d611ab36bd69a2794b5ddfc11dbf014c2ca
            - name: kind
              value: task
          resolver: bundles
      - name: push-dockerfile
        params:
          - name: IMAGE
            value: $(tasks.build-image-index.results.IMAGE_URL)
          - name: IMAGE_DIGEST
            value: $(tasks.build-image-index.results.IMAGE_DIGEST)
          - name: DOCKERFILE
            value: $(params.dockerfile)
          - name: CONTEXT
            value: $(params.path-context)
          - name: SOURCE_ARTIFACT
            value: $(tasks.prefetch-dependencies.results.SOURCE_ARTIFACT)
        runAfter:
          - build-image-index
        taskRef:
          params:
            - name: name
              value: push-dockerfile-oci-ta
            - name: bundle
              value: quay.io/konflux-ci/tekton-catalog/task-push-dockerfile-oci-ta:0.1@sha256:6fb61bec5ef161225a850005233db68cfdc03ad54e1a54cc49cc98d98ea3d259
            - name: kind
              value: task
          resolver: bundles
    workspaces:
      - name: git-auth
        optional: true
      - name: netrc
        optional: true
  taskRunTemplate:
    serviceAccountName: build-pipeline-forklift-operator-bundle-2-10
  workspaces:
    - name: git-auth
      secret:
        secretName: "{{ git_auth_secret }}"
status: {}
