apiVersion: forklift.konveyor.io/v1beta1
kind: CopyApplianceTemplate
metadata:
  name: nbdkit-copy-appliance-template
  namespace: copyApplianceTemplate-e2e
spec:
  provider:
    name: vcenter
    namespace: openshift-mtv
  baseDisk:
    containerImage: registry.redhat.io/rhel9/rhel-guest-image:latest
  templateName: nbdkit-copy-appliance-template
  datastore: datastore1
  folder: /Datacenter/vm
  network: "VM Network"
