// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/kubev2v/forklift/cmd/vsphere-xcopy-volume-populator/internal/populator (interfaces: Hostlocker)
//
// Generated by this command:
//
//	mockgen -destination=mocks/hostlocker_mock.go -package=mocks . Hostlocker
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockHostlocker is a mock of Hostlocker interface.
type MockHostlocker struct {
	ctrl     *gomock.Controller
	recorder *MockHostlockerMockRecorder
	isgomock struct{}
}

// MockHostlockerMockRecorder is the mock recorder for MockHostlocker.
type MockHostlockerMockRecorder struct {
	mock *MockHostlocker
}

// NewMockHostlocker creates a new mock instance.
func NewMockHostlocker(ctrl *gomock.Controller) *MockHostlocker {
	mock := &MockHostlocker{ctrl: ctrl}
	mock.recorder = &MockHostlockerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHostlocker) EXPECT() *MockHostlockerMockRecorder {
	return m.recorder
}

// WithLock mocks base method.
func (m *MockHostlocker) WithLock(ctx context.Context, hostID string, work func(context.Context) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithLock", ctx, hostID, work)
	ret0, _ := ret[0].(error)
	return ret0
}

// WithLock indicates an expected call of WithLock.
func (mr *MockHostlockerMockRecorder) WithLock(ctx, hostID, work any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithLock", reflect.TypeOf((*MockHostlocker)(nil).WithLock), ctx, hostID, work)
}
