apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- resources/forkliftcontroller.yaml
configMapGenerator:
- behavior: create
  envs:
  - deploy.env
  name: forklift-controller-env
replacements:
- source:
    fieldPath: data.OPERATOR_NAMESPACE
    kind: ConfigMap
    name: forklift-controller-env
    version: v1
  targets:
  - fieldPaths:
    - metadata.namespace
    select:
      group: forklift.konveyor.io
      kind: ForkliftController
      version: v1beta1
