---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: forkliftcontrollers.forklift.konveyor.io
spec:
  group: forklift.konveyor.io
  names:
    kind: ForkliftController
    listKind: ForkliftControllerList
    plural: forkliftcontrollers
    singular: forkliftcontroller
  scope: Namespaced
  versions:
  - name: v1beta1
    schema:
      openAPIV3Schema:
        description: ForkliftController is the Schema for the forkliftcontrollers API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: Spec defines the desired state of ForkliftController
            type: object
            properties:
              # Keep fields synchronized with operator/roles/forkliftcontroller/defaults/main.yml
              # This file defines all configurable options that users can override in ForkliftController CR
              # When adding/removing fields: update CRD schema and defaults/main.yml
              #
              # Source file is: operator/config/crd/bases/forklift.konveyor.io_forkliftcontrollers.yaml,
              # No need to edit other files, other files containing the CRD definitions are automatically updated.
              #
              # NOTE: This list was auto generated by an AI agent

              # Feature Gates
              feature_ui_plugin:
                type: string
                enum: ["true", "false"]
                description: "Enable UI plugin (default: true)"
              feature_validation:
                type: string  
                enum: ["true", "false"]
                description: "Enable validation service (default: true)"
              feature_volume_populator:
                type: string
                enum: ["true", "false"]  
                description: "Enable volume populators (default: true)"
              feature_copy_offload:
                type: string
                enum: ["true", "false"]
                description: "Enable copy offload plugins (default: false)"
              feature_ocp_live_migration:
                type: string
                enum: ["true", "false"]
              feature_ova_appliance_management:
                type: string
                enum: [ "true", "false" ]
                description: "Enable OCP live migration (default: false)"
              feature_vmware_system_serial_number:
                type: string
                enum: ["true", "false"]
                description: "Use VMware system serial numbers (default: true)"
              feature_auth_required:
                type: string
                enum: ["true", "false"]
                description: "Require authentication (default: true)"
              feature_cli_download:
                type: string
                enum: ["true", "false"]
                description: "Enable CLI download service (default: true)"

              # Container Images
              controller_image_fqin:
                type: string
                description: "Controller pod image"
                example: "quay.io/kubev2v/forklift-controller:latest"
              virt_v2v_image_fqin:
                type: string
                description: "Virt-v2v conversion image used by migration pods"
                example: "quay.io/kubev2v/forklift-virt-v2v:latest"
              vddk_image:
                type: string
                description: "VDDK image for VMware disk access"
                example: "quay.io/kubev2v/vddk:7.0.3"
              api_image_fqin:
                type: string
                description: "API service image"
                example: "quay.io/kubev2v/forklift-api:latest"
              cli_download_image_fqin:
                type: string
                description: "CLI download service image"
                example: "quay.io/kubev2v/forklift-cli-download:latest"
              ui_plugin_image_fqin:
                type: string
                description: "UI plugin image"
                example: "quay.io/kubev2v/forklift-ui-plugin:latest"
              validation_image_fqin:
                type: string
                description: "Validation service image"
                example: "quay.io/kubev2v/forklift-validation:latest"
              populator_controller_image_fqin:
                type: string
                description: "Volume populator controller image"
                example: "quay.io/kubev2v/populator-controller:latest"
              populator_ovirt_image_fqin:
                type: string
                description: "oVirt populator image"
                example: "quay.io/kubev2v/ovirt-populator:latest"
              populator_openstack_image_fqin:
                type: string
                description: "OpenStack populator image"
                example: "quay.io/kubev2v/openstack-populator:latest"
              populator_vsphere_xcopy_volume_image_fqin:
                type: string
                description: "vSphere xcopy populator image"
                example: "quay.io/kubev2v/vsphere-populator:latest"
              ova_provider_server_fqin:
                type: string
                description: "OVA provider server image"
                example: "quay.io/kubev2v/ova-provider-server:latest"
              must_gather_image_fqin:
                type: string
                description: "Must-gather debugging image"
                example: "quay.io/kubev2v/forklift-must-gather:latest"
              ova_proxy_fqin:
                type: string
                description: "OVA inventory proxy image"
                example: "quay.io/kubev2v/forklift-ova-proxy:latest"

              # Controller Resource Configuration
              controller_container_limits_cpu:
                type: string
                description: "Controller CPU limit (default: 500m)"
                example: "1000m"
              controller_container_limits_memory:
                type: string
                description: "Controller memory limit (default: 800Mi)"
                example: "1Gi"
              controller_container_requests_cpu:
                type: string
                description: "Controller CPU request (default: 100m)"
                example: "200m"
              controller_container_requests_memory:
                type: string
                description: "Controller memory request (default: 350Mi)"
                example: "500Mi"

              # Inventory Resource Configuration
              inventory_container_limits_cpu:
                type: string
                description: "Inventory CPU limit (default: 1000m)"
                example: "2000m"
              inventory_container_limits_memory:
                type: string
                description: "Inventory memory limit (default: 1Gi)"
                example: "2Gi"
              inventory_container_requests_cpu:
                type: string
                description: "Inventory CPU request (default: 500m)"
                example: "1000m"
              inventory_container_requests_memory:
                type: string
                description: "Inventory memory request (default: 500Mi)"
                example: "1Gi"

              # API Resource Configuration
              api_container_limits_cpu:
                type: string
                description: "API service CPU limit (default: 1000m)"
                example: "2000m"
              api_container_limits_memory:
                type: string
                description: "API service memory limit (default: 1Gi)"
                example: "2Gi"
              api_container_requests_cpu:
                type: string
                description: "API service CPU request (default: 100m)"
                example: "200m"
              api_container_requests_memory:
                type: string
                description: "API service memory request (default: 150Mi)"
                example: "300Mi"

              # CLI Download Resource Configuration
              cli_download_container_limits_cpu:
                type: string
                description: "CLI download service CPU limit (default: 100m)"
                example: "200m"
              cli_download_container_limits_memory:
                type: string
                description: "CLI download service memory limit (default: 128Mi)"
                example: "256Mi"
              cli_download_container_requests_cpu:
                type: string
                description: "CLI download service CPU request (default: 50m)"
                example: "100m"
              cli_download_container_requests_memory:
                type: string
                description: "CLI download service memory request (default: 64Mi)"
                example: "128Mi"

              # UI Plugin Resource Configuration
              ui_plugin_container_limits_cpu:
                type: string
                description: "UI plugin CPU limit (default: 100m)"
                example: "200m"
              ui_plugin_container_limits_memory:
                type: string
                description: "UI plugin memory limit (default: 800Mi)"
                example: "1Gi"
              ui_plugin_container_requests_cpu:
                type: string
                description: "UI plugin CPU request (default: 100m)"
                example: "200m"
              ui_plugin_container_requests_memory:
                type: string
                description: "UI plugin memory request (default: 150Mi)"
                example: "300Mi"

              # Validation Resource Configuration
              validation_container_limits_cpu:
                type: string
                description: "Validation CPU limit (default: 1000m)"
                example: "2000m"
              validation_container_limits_memory:
                type: string
                description: "Validation memory limit (default: 300Mi)"
                example: "500Mi"
              validation_container_requests_cpu:
                type: string
                description: "Validation CPU request (default: 400m)"
                example: "500m"
              validation_container_requests_memory:
                type: string
                description: "Validation memory request (default: 50Mi)"
                example: "100Mi"
              validation_policy_agent_search_interval:
                type: string
                description: "Policy agent search interval in seconds (default: 120)"
                pattern: "^[1-9][0-9]*$"

              # Migration Settings & Timeouts
              controller_max_vm_inflight:
                type: string
                description: "Max concurrent VM migrations (default: 20)"
                pattern: "^[1-9][0-9]*$"
              controller_precopy_interval:
                type: string
                description: "Precopy interval in minutes (default: 60)"
                pattern: "^[1-9][0-9]*$"
              controller_max_concurrent_reconciles:
                type: string
                description: "Max concurrent reconciles (default: 10)"
                pattern: "^[1-9][0-9]*$"
              controller_snapshot_removal_timeout_minuts:
                type: string
                description: "Snapshot removal timeout in minutes (default: 120)"
                pattern: "^[1-9][0-9]*$"
              controller_snapshot_status_check_rate_seconds:
                type: string
                description: "Snapshot status check rate in seconds (default: 10)"
                pattern: "^[1-9][0-9]*$"
              controller_cleanup_retries:
                type: string
                description: "Cleanup retry count (default: 10)"
                pattern: "^[1-9][0-9]*$"
              controller_dv_status_check_retries:
                type: string
                description: "DataVolume status check retries (default: 10)"
                pattern: "^[1-9][0-9]*$"
              controller_snapshot_removal_check_retries:
                type: string
                description: "Snapshot removal retries (default: 20)"
                pattern: "^[1-9][0-9]*$"
              controller_vddk_job_active_deadline_sec:
                type: string
                description: "VDDK job timeout in seconds (default: 300)"
                pattern: "^[1-9][0-9]*$"
              controller_tls_connection_timeout_sec:
                type: string
                description: "TLS connection timeout seconds (default: 5)"
                pattern: "^[1-9][0-9]*$"

              # Migration Feature-Specific Settings
              controller_vsphere_incremental_backup:
                type: string
                enum: ["true", "false"]
                description: "Use vSphere incremental backup (default: true)"
              controller_ovirt_warm_migration:
                type: string
                enum: ["true", "false"]
                description: "Enable oVirt warm migration (default: true)"
              controller_retain_precopy_importer_pods:
                type: string
                enum: ["true", "false"]
                description: "Retain precopy pods (default: false)"
              controller_static_udn_ip_addresses:
                type: string
                enum: ["true", "false"]
                description: "Enable static udn IP addresses feature (default: false)"

              # Storage & Performance Settings
              controller_filesystem_overhead:
                type: string
                description: "Filesystem overhead percentage (default: 10)"
                pattern: "^(0|[1-9][0-9]?|100)$"
              controller_block_overhead:
                type: string
                description: "Block overhead in bytes (default: 0)"
                pattern: "^[0-9]+$"

              # Virt-v2v Settings
              virt_v2v_container_limits_cpu:
                type: string
                description: "virt-v2v CPU limit (default: 4000m)"
                example: "8000m"
              virt_v2v_container_limits_memory:
                type: string
                description: "virt-v2v memory limit (default: 8Gi)"
                example: "16Gi"
              virt_v2v_container_requests_cpu:
                type: string
                description: "virt-v2v CPU request (default: 1000m)"
                example: "2000m"
              virt_v2v_container_requests_memory:
                type: string
                description: "virt-v2v memory request (default: 1Gi)"
                example: "2Gi"
              virt_v2v_dont_request_kvm:
                type: string
                enum: ["true", "false"]
                description: "Don't request KVM for virt-v2v"
              virt_v2v_extra_args:
                type: string
                description: "Additional arguments for virt-v2v"
                example: "--debug-overlays"
              virt_v2v_extra_conf_config_map:
                type: string
                description: "ConfigMap name containing extra virt-v2v configuration"

              # Hooks Settings
              hooks_container_limits_cpu:
                type: string
                description: "Hooks CPU limit (default: 1000m)"
                example: "2000m"
              hooks_container_limits_memory:
                type: string
                description: "Hooks memory limit (default: 1Gi)"
                example: "2Gi"
              hooks_container_requests_cpu:
                type: string
                description: "Hooks CPU request (default: 100m)"
                example: "200m"
              hooks_container_requests_memory:
                type: string
                description: "Hooks memory request (default: 150Mi)"
                example: "300Mi"

              # OVA Settings
              ova_container_limits_cpu:
                type: string
                description: "OVA CPU limit (default: 1000m)"
                example: "2000m"
              ova_container_limits_memory:
                type: string
                description: "OVA memory limit (default: 1Gi)"
                example: "2Gi"
              ova_container_requests_cpu:
                type: string
                description: "OVA CPU request (default: 100m)"
                example: "200m"
              ova_container_requests_memory:
                type: string
                description: "OVA memory request (default: 150Mi)"
                example: "300Mi"

              # OVA Proxy Settings
              ova_proxy_container_limits_cpu:
                type: string
                description: "OVA Proxy CPU limit (default: 1000m)"
                example: "2000m"
              ova_proxy_container_limits_memory:
                type: string
                description: "OVA Proxy memory limit (default: 1Gi)"
                example: "2Gi"
              ova_proxy_container_requests_cpu:
                type: string
                description: "OVA Proxy CPU request (default: 250m)"
                example: "200m"
              ova_proxy_container_requests_memory:
                type: string
                description: "OVA Proxy memory request (default: 512Mi)"
                example: "300Mi"

              # Logging & General Settings
              controller_log_level:
                type: string
                description: "Log verbosity level (default: 3)"
                pattern: "^([0-9]|10)$"
              image_pull_policy:
                type: string
                enum: ["Always", "IfNotPresent", "Never"]
                description: "Image pull policy (default: Always)"
              k8s_cluster:
                type: string
                enum: ["true", "false"]
                description: "Whether running on Kubernetes (vs OpenShift) (default: false)"
              
            additionalProperties: true
          status:
            description: Status defines the observed state of ForkliftController
            type: object
            x-kubernetes-preserve-unknown-fields: true
        type: object
    served: true
    storage: true
    subresources:
      status: {}
