#!/usr/bin/env bash
set -o pipefail
shopt -s nullglob

if [ -z "$V2V_provider"] ; then
    echo "Following environment needs to be defined:"
    echo
    echo "    V2V_provider"
    exit 1
fi

if [ "$V2V_provider" == "vsphere" ] ; then
  if [ -z "$V2V_libvirtURL" ] || \
      [ -z "$V2V_secretKey" ] || \
      [ -z "$V2V_vmName" ] ; then
      echo "Following environment needs to be defined:"
      echo
      echo "    V2V_libvirtURL, V2V_secretKey, V2V_vmName"
      exit 1
  fi
fi

if [ "$V2V_provider" == "ova" ] ; then
  if [ -z "$V2V_diskPath" ] || \
      [ -z "$V2V_vmName" ] ; then
      echo "Following environment needs to be defined:"
      echo
      echo "    V2V_diskPath, V2V_vmName"
      exit 1
  fi
fi

export LIBGUESTFS_PATH=/usr/lib64/guestfs/appliance

echo "Preparing virt-v2v"

# This variable is used to build the list of arguments for virt-v2v.
args=()

# Temporary storage location
DIR="/var/tmp/v2v"
mkdir -p $DIR
args=("${args[@]}"
    -o local
    -os "$DIR"
)

# Generate disk name suffix from disk number. E.g. "c" (as in "sdc") for
# 3rd disk.
gen_name() {
    local chars=({a..z})
    local cnt="${#chars[@]}"
    local i=$(($1 % cnt))
    local rest=$(($1 / cnt))
    local prefix=""
    if [ $rest -gt 0 ] ; then
        prefix="$(gen_name $rest)"
    fi
    echo "$prefix${chars[$i-1]}"
}

# Disks on filesystem storage.
# e.g.: /mnt/disks/disk0/disk.img -> vmName-sda
for disk in /mnt/disks/disk[0-9]* ; do
	num="${disk:15}"
	ln -s "$disk/disk.img" "$DIR/$V2V_vmName-sd$(gen_name "$((num+1))")"
done
# Disks on block storage.
# e.g.: /dev/block0 -> vmName-sda
for disk in /dev/block[0-9]* ; do
	num="${disk:10}"
	ln -s "$disk" "$DIR/$V2V_vmName-sd$(gen_name "$((num+1))")"
done

if [ "$V2V_provider" == "vsphere" ] ; then
  # Store password to file
  echo -n "$V2V_secretKey" > "$DIR/vmware.pw"
  args=("${args[@]}"
      -ip "$DIR/vmware.pw"
  )

  # Use VDDK if present
  if [ -d "/opt/vmware-vix-disklib-distrib" ]; then
      args=("${args[@]}"
          -it vddk
          -io vddk-libdir=/opt/vmware-vix-disklib-distrib
          -io "vddk-thumbprint=$V2V_thumbprint"
      )
  fi
fi

echo "Starting virt-v2v"
set -x
ls -l "$DIR"
if [ "$V2V_provider" == "vsphere" ] ; then
  exec virt-v2v -v -x \
      -i libvirt \
      -ic "$V2V_libvirtURL" \
      "${args[@]}" \
      -- "$V2V_vmName" |& /usr/local/bin/virt-v2v-monitor
fi

if [ "$V2V_provider" == "ova" ] ; then
  exec virt-v2v -v -x \
      -i ova "$V2V_diskPath" \
      "${args[@]}" \
      |& /usr/local/bin/virt-v2v-monitor
fi
