FROM quay.io/operator-framework/ansible-operator:main

COPY requirements.yml ${HOME}/requirements.yml
COPY watches.yaml ${HOME}/watches.yaml
COPY roles ${HOME}/roles

RUN ansible-galaxy collection install -r ${HOME}/requirements.yml \
 && chmod -R ug+rwx ${HOME}/.ansible