apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: konveyor-forklift
  namespace: openshift-marketplace
spec:
  displayName: Liran Rotenberg
  publisher: Konveyor
  sourceType: grpc
  image: quay.io/lrotenbe/forklift-operator-index:latest
  updateStrategy:
    registryPoll:
      interval: 10m0s
