// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/kubev2v/forklift/pkg/lib/client/vsphere (interfaces: VIBEnsurer)
//
// Generated by this command:
//
//	mockgen -destination=mocks/vib_ensurer_mock.go -package=vsphere_mocks . VIBEnsurer
//

// Package vsphere_mocks is a generated GoMock package.
package vsphere_mocks

import (
	context "context"
	reflect "reflect"

	vmware "github.com/kubev2v/forklift/pkg/lib/client/vsphere/vmware"
	object "github.com/vmware/govmomi/object"
	gomock "go.uber.org/mock/gomock"
)

// MockVIBEnsurer is a mock of VIBEnsurer interface.
type MockVIBEnsurer struct {
	ctrl     *gomock.Controller
	recorder *MockVIBEnsurerMockRecorder
}

// MockVIBEnsurerMockRecorder is the mock recorder for MockVIBEnsurer.
type MockVIBEnsurerMockRecorder struct {
	mock *MockVIBEnsurer
}

// NewMockVIBEnsurer creates a new mock instance.
func NewMockVIBEnsurer(ctrl *gomock.Controller) *MockVIBEnsurer {
	mock := &MockVIBEnsurer{ctrl: ctrl}
	mock.recorder = &MockVIBEnsurerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVIBEnsurer) EXPECT() *MockVIBEnsurerMockRecorder {
	return m.recorder
}

// EnsureVib mocks base method.
func (m *MockVIBEnsurer) EnsureVib(ctx context.Context, client vmware.Client, esx *object.HostSystem, localVibPath string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnsureVib", ctx, client, esx, localVibPath)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnsureVib indicates an expected call of EnsureVib.
func (mr *MockVIBEnsurerMockRecorder) EnsureVib(ctx, client, esx, localVibPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnsureVib", reflect.TypeOf((*MockVIBEnsurer)(nil).EnsureVib), ctx, client, esx, localVibPath)
}
