storageVendorProduct: "flashsystem"
hostName: host-1007
tests:
  - name: test-1
    success:
      maxTimeSeconds: 300
    vms:
      - namePrefix: testvm1
        size: 10Gi
        localVmdkPath: 'assets/cloudinit/fedora.vmdk'