name: Build and Push Container Image

on:
  push:
    branches:
      - vsphere-xcopy-volume-populator-hal-api 

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Podman
        run: |
          sudo apt update
          sudo apt install -y podman

      - name: Log in to GitHub Container Registry (GHCR)
        run: |
          echo "${{ secrets.GHCR_TOKEN }}" | podman login ghcr.io -u $GITHUB_ACTOR --password-stdin

      - name: Build Container Image
        run: |
          make CONTAINER_CMD=$(which podman) build-vsphere-xcopy-volume-populator-image REGISTRY=ghcr.io REGISTRY_ORG=tatsumir

      - name: Push Container Image
        run: |
          make CONTAINER_CMD=$(which podman) push-vsphere-xcopy-volume-populator-image REGISTRY=ghcr.io REGISTRY_ORG=tatsumir

