name: Validate .tekton references
on:
  pull_request:
    types:
      - opened
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Check for tekton pipeline updates
        run: |
          if [[ -n $(SKIP_UPDATE=true ./update-tekton.sh .tekton/*) ]]; then
            echo "Konflux pipelines are outdated. Please update them by running 'make update-tekton'."
            exit 1
          else
            echo "Konflux pipelines are up to date."
            exit 0
          fi;
