name: Validate ForkliftController CRD
on:
  pull_request:
    paths:
      - "operator/config/crd/**"
      - "operator/roles/forkliftcontroller/**"
      - "hack/validate_forklift_controller_crd.py"

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyYAML
      - name: Validate ForkliftController CRD
        run: |
          python3 hack/validate_forklift_controller_crd.py
